# Generated by Django 2.2.5 on 2020-05-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pages',
            field=models.ImageField(null=True, upload_to='images/<django.db.models.fields.IntegerField>'),
        ),
    ]
