# Generated by Django 2.2.5 on 2020-05-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_chapter_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='pages',
        ),
    ]
