# Generated by Django 2.2.5 on 2020-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_type_images/'),
        ),
    ]
